//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Acc_MenuNavigationSpice
{
    protected System.Web.UI.WebControls.Button btnCheck;
    protected System.Web.UI.WebControls.Panel pnlhd;
    protected System.Web.UI.WebControls.Panel pnlhd1;
    protected System.Web.UI.WebControls.Panel pnlhd2;
}
