//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Acc_PopUp_ListSpice
{
    protected UserControl_GridFooter UCFooter;
    protected System.Web.UI.WebControls.GridView grdResult;
}
