//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_ConfirmPassword
{
    protected System.Web.UI.WebControls.TextBox txtConPassword;
    protected System.Web.UI.WebControls.TextBox txtPassword;
}
