//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_Controller
{
    protected System.Web.UI.WebControls.Button btnDelete;
    protected System.Web.UI.WebControls.Button btnReset;
    protected System.Web.UI.WebControls.Button btnSubmit;
    protected System.Web.UI.WebControls.CustomValidator cvdeleteyes;
    protected System.Web.UI.WebControls.HyperLink hpLink;
    protected System.Web.UI.WebControls.Label lblUpdatedloc;
    protected System.Web.UI.WebControls.Label lblcreatedby;
    protected System.Web.UI.WebControls.Label lblcreateddate;
    protected System.Web.UI.WebControls.Label lblcreatedloc;
    protected System.Web.UI.WebControls.Label lblupdatedby;
    protected System.Web.UI.WebControls.Label lblupdateddate;
    protected System.Web.UI.WebControls.Panel pnconfirmation;
    protected System.Web.UI.WebControls.Panel pninfo;
    protected System.Web.UI.WebControls.RadioButton rbyes;
}
