//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_EmailField
{
    protected System.Web.UI.HtmlControls.HtmlGenericControl pnlEmail;
    protected System.Web.UI.WebControls.RegularExpressionValidator reEmail;
    protected System.Web.UI.WebControls.RequiredFieldValidator rfEmail;
    protected System.Web.UI.WebControls.TextBox txtEmail;
}
