//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_ErrorReport
{
    protected System.Web.UI.WebControls.ValidationSummary vsSummary;
}
