//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class UserControl_GridFooter
{
    protected System.Web.UI.WebControls.ImageButton btnFirst;
    protected System.Web.UI.WebControls.ImageButton btnLast;
    protected System.Web.UI.WebControls.ImageButton btnNext;
    protected System.Web.UI.WebControls.ImageButton btnPrevious;
    protected System.Web.UI.WebControls.DropDownList ddlPage;
    protected System.Web.UI.WebControls.Label lblTotalRecord;
}
