//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class UserControl_GridHeader
{
    protected System.Web.UI.WebControls.DropDownList ddlAction;
    protected System.Web.UI.HtmlControls.HtmlAnchor hypAdd;
}
