//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_RangeValidator
{
    protected System.Web.UI.WebControls.CompareValidator cvCheckType1;
    protected System.Web.UI.WebControls.CompareValidator cvCheckType2;
    protected System.Web.UI.WebControls.CompareValidator cvRange;
    protected System.Web.UI.WebControls.RequiredFieldValidator rfBox1;
    protected System.Web.UI.WebControls.RequiredFieldValidator rfbox2;
    protected System.Web.UI.WebControls.TextBox txtbox1;
    protected System.Web.UI.WebControls.TextBox txtbox2;
}
