//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Search
{
    protected System.Web.UI.WebControls.Button btnMinus;
    protected System.Web.UI.WebControls.Button btnReset;
    protected System.Web.UI.WebControls.CheckBox chkDeleted;
    protected System.Web.UI.WebControls.DropDownList ddlOperator1;
    protected System.Web.UI.WebControls.DropDownList ddlSearch;
    protected System.Web.UI.WebControls.DropDownList ddlSearch2;
    protected System.Web.UI.WebControls.DropDownList ddlSearchUsing;
    protected System.Web.UI.WebControls.Label lblSearch;
    protected System.Web.UI.WebControls.Panel pnlAdvance;
    protected System.Web.UI.WebControls.Panel pnlBasic;
    protected System.Web.UI.WebControls.ListBox searchCriteria;
    protected System.Web.UI.WebControls.TextBox txtSearch;
    protected System.Web.UI.WebControls.TextBox txtSearchUsing;
}
