//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_Title
{
    protected System.Web.UI.WebControls.Label lblFormTitle;
}
