//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Style2_MenuPrai
{
    protected System.Web.UI.HtmlControls.HtmlAnchor ahrefhome;
}
