//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Style2_MenuSpice
{
    protected System.Web.UI.HtmlControls.HtmlAnchor ahrefhome;
    protected System.Web.UI.WebControls.Literal liItems;
}
