//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to provide field declarations for WebForms controls.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Log
{
    protected System.Web.UI.HtmlControls.HtmlGenericControl divDesc;
}
